# Generated by Django 2.1.5 on 2019-09-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='catergory',
            field=models.IntegerField(),
        ),
    ]
